language_model_base:
    emsize: 400
    nhid: 800
    nlayers: 3
    lr: 0.002
    weight_decay: 0.00001
    clip: 0.25
    epochs: 20
    batch_size: 20
    bptt_seq_len: 70
    bptt_random_scaling: 2.0
    bptt_p: 0.95
    bptt_s: 5
    bptt_min_len: 5
    bptt_max_len: 80
    dropout: 0.2
    weight_tying: true
    save: 'model.pt'
    weight_drop: 0.5

text_generation_base:
    checkpoint: 'model.pt'
    outf: 'generated.txt'
    words: 1000
    temperature: 1
    
text_generation_beam_search:
    checkpoint: 'model.pt'
    outf: 'generated_beam.txt'
    words: 50
    beam_size: 100
